### 1. Write a Python Program to Add Two Matrices?

In [4]:
import numpy as np
a = np.array(((1,2,3),(5,4,6),(9,1,2)))
b = np.array(((9,9,9),(4,9,2),(3,7,5)))

In [15]:
sum = np.add(a,b)

### 2. Write a Python Program to Multiply Two Matrices?

In [20]:
multiply2 = np.dot(a,b)

In [22]:
multiply2

array([[ 26,  48,  28],
       [ 79, 123,  83],
       [ 91, 104,  93]])

### 3. Write a Python Program to Transpose a Matrix?

In [27]:
a

array([[1, 2, 3],
       [5, 4, 6],
       [9, 1, 2]])

In [25]:
transpose = a.T

In [26]:
transpose

array([[1, 5, 9],
       [2, 4, 1],
       [3, 6, 2]])

### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [39]:
lst = ['z','b','d','q','m','a','c','cba','mno']
l2 = sorted(lst)

In [41]:
l2

['a', 'b', 'c', 'cba', 'd', 'm', 'mno', 'q', 'z']

### 5. Write a Python Program to Remove Punctuation From a String?

In [53]:
import re
string = """She is running late.' This is a sentence.'She is' isn't a complete sentence 
         unless it is an answer to a question. (Is she running late? She is.)Sentences can contain one 
         statement:'I fed the dog.'or more than one statement:'I fed the dog and then 
         I went to the pet shop to buy more dog food."""

In [54]:
string = re.sub(r'[^\w\s]', '', string)

In [56]:
print(string)

She is running late This is a sentenceShe is isnt a complete sentence 
         unless it is an answer to a question Is she running late She isSentences can contain one 
         statementI fed the dogor more than one statementI fed the dog and then 
         I went to the pet shop to buy more dog food
